version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container-cse
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: code_space_editor
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_cse:/var/lib/mysql
    
  mongodb:
    image: mongo:6.0
    container_name: mongo-container-cse
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: code_space_editor_mongo
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo_data_cse:/data/db

volumes:
  mysql_data_cse:
  mongo_data_cse: